[package]
name = "stagemaster-previs"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
stagemaster-project = { path = "../stagemaster-project" }
stagemaster-spatial = { path = "../stagemaster-spatial" }
serde = { version = "=1.0.229", features = ["derive"] }

[lints]
workspace = true

[dev-dependencies]
serde_json = "=1.0.151"
