[package]
name = "stagemaster-install-worker"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
stagemaster-install = { path = "../stagemaster-install" }
stagemaster-transfer = { path = "../stagemaster-transfer" }

[dev-dependencies]
stagemaster-install-store = { path = "../stagemaster-install-store" }
stagemaster-package = { path = "../stagemaster-package" }
stagemaster-project = { path = "../stagemaster-project" }
tempfile = "=3.27.0"
serde_json = "=1.0.151"

[lints]
workspace = true
