[package]
name = "jsonschema-regex"
version = "0.57.0"
description = "ECMA 262 regex translation for the jsonschema crate"
rust-version.workspace = true
edition.workspace = true
authors.workspace = true
repository.workspace = true
license.workspace = true

[dependencies]
regex-syntax = "0.8.9"

[dev-dependencies]
regex = "1.11.1"
test-case = "3"

[lints]
workspace = true
