[package]
name = "stagemaster-output-port"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[features]
queued-dmx = ["dep:embassy-sync"]

[dependencies]
embassy-sync = { version = "=0.8.0", optional = true }

[dev-dependencies]
critical-section = { version = "=1.2.0", features = ["std"] }
stagemaster-runtime = { path = "../stagemaster-runtime" }
stagemaster-project = { path = "../stagemaster-project" }
stagemaster-package = { path = "../stagemaster-package" }
stagemaster-install = { path = "../stagemaster-install" }
stagemaster-install-store = { path = "../stagemaster-install-store" }
serde_json = "=1.0.151"
tempfile = "=3.27.0"

[lints]
workspace = true
