[package]
name = "stagemaster-project-store"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
stagemaster-package = { path = "../stagemaster-package" }
stagemaster-project = { path = "../stagemaster-project" }
tempfile = "=3.27.0"
serde = { version = "=1.0.229", features = ["derive"] }
serde_json = { version = "=1.0.151", features = ["raw_value"] }
sha2 = "=0.10.9"
uuid = { version = "=1.26.1", features = ["v4"] }

[lints]
workspace = true
